department-of-veterans-affairs/vagov-content

- pages/index.md
- scripts/heroku-postbuild.sh
This PR adds the front matter used to render the Metalsmith template being added at https://github.com/department-of-veterans-affairs/vets-website/pull/8899.
Todo
> Add metadata for homepage alert banner

- pages/housing-assistance/index.md
This fixes the missing facility locator link in the alert on housing assistance.
Related: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14346
> Fix facility locator link on housing assistance page

- pages/disability/va-claim-exam.md
- pages/housing-assistance/home-loans/eligibility.md
- pages/housing-assistance/home-loans/how-to-apply.md
There's an extra div in this page, which pushes the content down.
Related to: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14761
> Remove extra div in how to apply page

- pages/404.md
When using search.gov's hosted pages, we were passing &utf8=✓&affiliate=va into the URL as required by their docs. We can safely remove these now that we're using a vets-api based approach.
See issue [#14795](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14795)
See sibling pr in vets-website [here](https://github.com/department-of-veterans-affairs/vets-website/pull/8981)
Verified locally that when submitting a search the params are not including in the URL. 
Verified on [heroku build](https://vagov-content-pr-91.herokuapp.com/) that change is present.
> Remove extraneous fields from search form

- pages/logout.md
The popup isn't closing and localstorage isn't being cleared because we loose the parameter
success=true in a redirect, possibly from nginx.  This will put a bandaid on the typical user
experience
> Temporary fix:  logout redirect

- pages/connected-accounts/index.md
- pages/disability-benefits/apply/form-526-all-claims.md
- pages/search.md
This PR removes pages from the future www.va.gov that are hidden from preview.va.gov by adding `vagovprod: false` in the front matter.
Move to validate https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14822
> Hide pages from www.va.gov that are currently hidden from preview.va.gov

- package.json
With the Vets.gov dev environment being deprecated and the content deployment being revisited, we need to remove the `--content-deployment` flag from the Heroku review instances and instead just compile the static pages bundle as usual.
> Patch for Heroku review instances after deprecating Vets.gov dev

- pages/life-insurance/manage-your-policy.md
**Steps to reproduce:**
On this page:
https://preview.va.gov/life-insurance/manage-your-policy/
Click on the last link on the page: "Find your policy through Prudential Insurance Company of America." It should open in a pop-up but doesn't. 
**Expected behavior:**
The link should open a pop-up. Here's how the link should be structured to achieve this:
<a data-popup href="https://giosgli.prudential.com/osgli/web/OSGLIMenu.html">Find your policy through Prudential Insurance Company of America</a>
Local testing
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14044
> Life Insurance link to Prudential website opens in a popup

- pages/burials-memorials/replace-medals-awards-and-decorations.md
The link for "Replace Medals, Awards, and Decorations is incorrect.  
The option should link here: www.archives.gov/veterans/replace-medals
This is an external link and should continue to open in a new tab/window and should have the external link icon next to it. 
It now links to the correct site
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14483
> Fixes Link in Burials Left Nav

- pages/change-direct-deposit-and-contact-information.md
The button to go to eBenefits on the Change Your Direct Deposit or Contact Information page does not work.
Should link to eBenefits and open in a new tab.
This PR refactors button to be an external link, in keeping with the manner in which other buttons that link to external sites, in a new tabs, do elsewhere in the codebase.
Button now opens to the below URL, in a new tab:
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14838
> Fixes button to eBenefits on Direct Deposit page

- pages/education/opt-out-information-sharing.md
From [vets-gov/#14614](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14614)
> Left Nav is not loading correctly on this page:
https://preview.va.gov/education/opt-out-information-sharing/
> Given this page is not accessible from the left nav, we should remove the left nav from it. This page is intentionally not linked to from anywhere in navigation.
This PR is proposed as an interim solution until post-launch, where further work can be extended to allow for a template sans-left-navbar.
> [WIP] Fix sidebar on education opt-out page

- pages/disability/file-for-increased.md
Issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14911
Added "File for Increased Disability"  as second option in the left nav, just below Check Claim or Appeal Status.  
It should link to: https://preview.va.gov/disability-benefits/apply/form-526-disability-claim/introduction
> Add file for increased disability link to sidebar

- redirects/vets-gov-to-va-gov.yml
Noted here, https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13928#issuecomment-437114031, `https://www.vets.gov/welcome-to-va/` should point to `https://www.va.gov/welcome-kit/`.
> Add a redirect for the Welcome Kit

- pages/records/get-veteran-id-cards/vic.md
We have a preprod VIC account link in our content when we shouldn't. This should just go to production.
> Fix preprod VIC link

- pages/disability/after-you-file-claim.md
This PR updates the link on https://va.gov/disability/after-you-file-claim/ to not load the login modal. See [issue](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14405) for more context.
> Change href of link to point to non-auth page

- redirects/vets-gov-to-va-gov.yml
I think maybe we had this and I removed it? We need to keep any react apps in this list that changed urls and need to retain their path.
Related to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15019
> Add redirect for facilities

- pages/housing-assistance/home-loans/how-to-apply.md
Expand "Surviving spouse of a Veteran who died on active duty or who had a service-connected disability."
The following links are oddly spaced:
Download VA Form 21P-534EZ.
Find out if you qualify for home loan benefits.
Get military service records online.
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15015
> Fixes link spacing on How to Apply for a VA Home Loan COE

- pages/records/get-military-service-records.md
and deleting "what kind of account do i need" question
url: https://www.va.gov/records/get-military-service-records/
Internal decision to move instructions re: how to request records once signed in to milConnect up to make more visible to users.
- Move instructions up
- Remove "what kind of account do i need" question because it's redundant
> moving instructions up on page

- package.json
Leaving the `--brand-consolidation-enabled` flag throws an error, and needs to be removed for Heroku review instances to work.
> Remove WBC flag

- pages/404.md
- pages/503.html
- pages/maintenance.md
This pull request updates a few `include` statements to reference the `src/site` directory, rather than the `va-gov` directory. This is based on some restructuring to `vets-website`. After this, the `va-gov` directory can be removed from `vets-website`.
This has to be merged after https://github.com/department-of-veterans-affairs/vets-website/pull/9127.
> Change references to use src/site

- redirects/vets-gov-to-va-gov.yml
This PR implements the redirects as described in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15001, and in association with the server-side redirects being removed in https://github.com/department-of-veterans-affairs/devops/pull/3699.
> Add redirects for remaining employment pages

- fragments/home/banner.yml
This adds some comments into the alert banner config so that editors can easily see what each property is.
> Add some comments so that an editor knows what alert-types there are

- redirects/vets-gov-to-va-gov.yml
Currently, `https://www.va.gov/health-care/medical-information-terms-conditions` is inaccessible, because it was to be retired in favor of MHV terms and conditions. However, the latter is still a work in progress, so we have to re-enable this page for users to complete the MHC account creation flow.
Ticket here, https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15620
> Remove the Vets-to-VA redirect for Terms and Conditions

- pages/health-care/index.md
This alias should have been removed in this PR, https://github.com/department-of-veterans-affairs/vagov-content/pull/181, but I missed it. The Terms and Conditions app is still necessary at the moment.
> Remove alias for Terms and Conditions

- pages/health-care/health-needs-conditions/mental-health.md
Per the ticket here, https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15532, a brochure will soon be distributed that will contain a link to `/mental-health-services`, but that should redirect to `/health-needs-conditions/mental-health/`. This PR adds an alias to handle this.
> Add a redirect for "/mental-health-services"

- pages/sign-in-faq.md
This PR removes the local redirect from `/faq` to `/sign-in-faq` per this ticket, https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15818.
> Remove redirect from /faq to /sign-in-faq

- pages/health-care/about-va-health-benefits.md
url: /health-care/about-va-health-benefits
Bug - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14992
Remove the link to Vets.gov, which is causing an intermediary redirect before the user lands on Find Locations with the Vets.gov-to-VA.gov popup
> Remove Vets.gov link

- pages/404.md
url: pages/404.md
Internal. Connected to this ticket: https://github.com/department-of-veterans-affairs/vets-website/pull/9381
Removed the reference to usa-search.js in pages/404.md since we now have our own search functionality integrated into va.gov.
> Removed usa-search.js script

- .github/CODEOWNERS
The codeowners file was only working properly for files at the root of `pages/`, but we want it to trigger for all files.
Per the [docs](https://help.github.com/articles/about-code-owners/), this should fix it.
```
docs/*  docs@example.com
...
/docs/ @doctocat
```
> [Codeowners] Fix for nested files

- package.json
The PR upgrade Yarn to be consistent with [`vets-website`](https://github.com/department-of-veterans-affairs/vets-website/blob/f105ed14f7606c0ec5e67b3b3201ed25871258a6/package.json#L183). It may also resolve a Heroku build error occurring during the Font Awesome upgrade.
> Upgrade Yarn

- .github/CODEOWNERS
Sometimes @Hampshire100 needs to publish a change to the homepage, such as a change to the banner or the news articles. I’m usually assigned for review, but in my absence I want to make sure other engineers are aware. Usually these changes have to be published same day.
> Add code owners for homepage 

- pages/sign-in-faq.md
url: https://www.va.gov/sign-in-faq/
We are linking to the sign in FAQ if the user encounters an error signing it.  Upon arriving on the faq page, the first question in the "Common issues with signing in to VA.gov" should be auto expanded. Add additional JS code to auto expand accordion based on URL hash
> Add #sign-in-issue to open accordion switch

- pages/health-care/eligibility.md
url: https://www.va.gov/health-care/eligibility/
> Fixing nexted question markdown on eligibility page.

- pages/decision-reviews/higher-level-review.md
- pages/decision-reviews/supplemental-claim.md
url: 
```
/decision-reviews/supplemental-claim/
/decision-reviews/higher-level-review/
```
internal
This PR fixes the axe-core bug found in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16981 where the `process-accordion` was failing the jenkins build.
**Solution**: took out `area-multiselectable` property and added an `<li>`.
I also added a class for proper styling in `vets-website` repo in `merger.scss`.
> [Bug] axe-core issue with accordion for AMA pages

- pages/disability/file-disability-claim-form-21-526ez.md
*Note:* The diff makes it difficult to tell, but the existing page was _deleted_, renamed, and recreated (i.e., 'moved') in a different directory
url: /disability-benefits/apply/form-526-all-claims
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15793
1.) Remove current path / page for the v2 526 form
2.) Add a new path / page for the v2 526 form, at `disability/file-disability-claim-form-21-526ez/`
3.) Navigation breadcrumb link for the 526 v2 form needs to reflect the new URL
Redirects from the old to new url will be handled in a separate devops PR
Related PRs:
Devops: https://github.com/department-of-veterans-affairs/devops/pull/4190
Website: https://github.com/department-of-veterans-affairs/vets-website/pull/9605
> Add page for disability v2 app, remove old page

- pages/dst/index.md
url: /dst
Appeals team
> We’re looking to help set up a one page demo with live staging url that the appeals team can use. We landed on having them create a page in `vagov-content` where they could write vanilla inline JS and have the page gated to the staging environment.
A page at `/dst` that builds to Staging only
> [Appeals] Add Staging-only page

- docs/front-matter.md
n/a
Internal. Documenting what happened [here](https://github.com/department-of-veterans-affairs/vagov-content/pull/283).
Adding documentation on `vagovprod` to front matter documentation.
> Add production flag to front matter doc.

- pages/decision-reviews/index.md
This should be done on the server, but became more complicated than expected. See linked ticket for details.
url: /decision-reviews
See https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17108
Redirect
> Add redirect from /decision-review to /decision-reviews

- pages/careers-employment/vocational-rehabilitation.md
- pages/careers-employment/vocational-rehabilitation/programs.md
- pages/health-care/health-needs-conditions/health-issues-related-to-service-era.md
- pages/life-insurance/options-eligibility.md
urls: 
- /health-care/health-needs-conditions/health-issues-related-to-service-era/
- /life-insurance/options-eligibility/
- /careers-employment/vocational-rehabilitation/
- /careers-employment/vocational-rehabilitation/programs/
internal.  https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/14994
Added front matter flag `no_article_bottom_padding` to page. When set to true, it removes the default `padding-bottom: 3em` property set to the `article` class
**before**:
**after**: 
More info on edits to the page layout on `vets-website` found in this PR: https://github.com/department-of-veterans-affairs/vets-website/compare/fix-article-content-bottom-padding-14994?expand=1
> Remove bottom padding between content and major links section

- pages/health-care/about-va-health-benefits.md
- pages/health-care/after-you-apply.md
- pages/health-care/eligibility.md
- pages/health-care/family-caregiver-benefits/champva.md
- pages/health-care/get-medical-records.md
- pages/health-care/health-needs-conditions/mental-health.md
- pages/health-care/how-to-apply.md
- pages/health-care/index.md
- pages/health-care/order-hearing-aid-batteries-prosthetic-socks.md
- pages/health-care/refill-track-prescriptions/index.md
- pages/health-care/schedule-view-va-appointments.md
A number of pages, but there will be no visible difference to any of them. 
Drupal CMS as currently configured doesn't support `<b>`, partly because  
> According to the HTML 5 specification, the `<b>` tag should be used as a LAST resort when no other tag is more appropriate. The HTML 5 specification states that headings should be denoted with the `<h1>` to `<h6>` tags, emphasized text should be denoted with the `<em>` tag, important text should be denoted with the `<strong>` tag, and marked/highlighted text should use the `<mark>` tag.
We could allow it to support `<b>`, but it really shouldn't, since editors won't be able to use it in the future with WYSIWYG editor. 
Change all `<b>` tags to `<strong>` tags.
Read diff closely to make sure all `<`, `>` and `/` remain the same. The only …
> Change all <b> tags to <strong> tags in health care hub content.

- pages/health-care/schedule-view-va-appointments.md
url: https://www.va.gov/health-care/schedule-view-va-appointments/
developer: CMS Migration
The migration script expects alerts with the same name (heading) to be identical across all of the pages where it is used. On other pages, the "How do I talk to someone right now?" alert has the class attribute after the href on the chat link.
This is an internal (html) change only. Nothing about the page should be different.
> Move class declaration for consistency with other alerts.

- Jenkinsfile
This notification is spamming the oncall channel and needs to be revisited before we can turn it back on.
> Disable Slack message

- pages/careers-employment/index.md
- pages/health-care/index.md
- pages/housing-assistance/index.md
url: 
```
/housing-assistance/
/careers-employment/
/health-care/
```
internal from @nedierecel
This purpose of this PR is to add `'event': 'nav-crisis-homelessness-expander'` on the "We may be able to help" link in the homeless alert box on the urls above.
> [Analytics] Add Homeless Expander GA event

- pages/privacy.md
url: `/privacy/`
internal (@WinishaSmith 
The purpose of this PR is to adjust the `<h1>` at the top of the page to be left-aligned.
I accomplished this by changing the template from `leve2-index`. to `detail-page`.
**Before**:
**After**:
> [Bug] Fix H1 on Privacy Page to Left-Aligned

- package.json
This PR removes a flag from the Heroku builds that was only there for reviewing a previous PR.
> Remove flag from commit that should have been reverted

- fragments/megamenu/index.yml
The links to the Service Member hub and Family Member hub in the MegaMenu aren't resolving properly on TeamSite pages. They should have been absolute URLs instead of relative.  Example - https://www.benefits.va.gov/compensation/dbq_disabilityexams.asp.
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18280
> [MegaMenu] Fix for links not resolving properly on TeamSite pages

- pages/decision-reviews/faq.md
<section class="usa-grid usa-grid-full">
<div class="va-h-ruled--stars"></div>
</section>
url: https://www.va.gov/decision-reviews/faq/
this is the only use of va-h-ruled--stars on a benefit detail page (they are used within benefits as a separator between spokes). @jenniferlee-dsva suggested this one is rogue. 
Remove hr
> Remove rogue va-h-ruled--stars.

- pages/pension/pension-management-centers.md
url: https://www.va.gov/pension/pension-management-centers/
Content anomaly: CMS body fields will not support grid layouts.
Remove grid layout.
> Remove two column layout for state listings on Pension Management page.

- pages/education/index.md
url: va.gov/education
"On this page" header is an `<h3>` for all hubs except education, where it was an `<h2>`.  This commit standardizes.
Replace `<h2>` with `<h3>`
> Make Education's "On this page" an <h3>, like other hubs.

- pages/decision-reviews/get-help.html
There is a server-side redirect for `/decision-reviews/get-help/`. However, we also need to capture the case without the trailing slash. We can't add that to the server without creating a redirect loop, because the server-side redirects are greedy and try to redirect any routes that match `/decision-review/get-help*`. There is a Devops ticket to change this but the work is ongoing, https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17486.
We can no longer add FE `aliases`, because the work migrating content into the CMS causes us to lose those values. So, we're at a tough spot, and just adding this here seems to be the only way we can do this.
> Add redirect for /decision-reviews/get-help

- pages/records/get-veteran-id-cards.md
url: https://www.va.gov/records/get-veteran-id-cards/
Via migration QA we found a small bug in the original content
Remove the empty `relatedlinks:` so that this grey line doesn't show up.
> Remove empty 'relatedlinks:' frontmatter on Get Veteran ID cards page.

- pages/decision-reviews/board-appeal/veterans-law-judge-hearing.md
url: /decision-reviews/board-appeal/veterans-law-judge-hearing/
Internal (@bethpotts)
This PR fixes an issue where the text went passed the right margin on `/decision-reviews/board-appeal/veterans-law-judge-hearing/`
**before**:
**after**:
> Fixed right margin on veterans law judge page

- pages/dst/index.md
url: /dst
We're removing this from the sitemap, since it's a test page that is never going to be a real part of the site.
> Remove dst from sitemap

- fragments/home/banner.yml
Remove the outage banner that was put up for the 2019-05-29 outage.
> Remove 2019-05-29 Outage Banner

- package.json
This PR updates the version of Node to match that of https://github.com/department-of-veterans-affairs/vets-website/pull/10111. Heroku throws an error otherwise.
> Update Node.js version

- pages/logout.md
url: /logout
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18834
`sessionStorage.shouldRedirectExpiredSession` should be cleared on log out.
> Remove sessionStorage.shouldRedirectExpiredSession on logout

- pages/careers-employment/vocational-rehabilitation/programs/self-employment.md
url: https://www.va.gov/careers-employment/vocational-rehabilitation/programs/self-employment/
CMS migration team discovered anomaly in related link. Can't have a separate heading with a link within the rest of the related links. 
Deleted the "More support for your small business" head, text and related link.
> Careers page anomaly fix

- pages/burials-memorials/veterans-burial-allowance.md
- pages/disability/eligibility.md
- pages/disability/how-to-file-claim.md
- pages/education/eligibility.md
- pages/education/how-to-apply.md
- pages/education/opt-out-information-sharing.md
- pages/pension/eligibility.md
- pages/pension/how-to-apply.md
This updates the static widget markup on several pages to use the same output as the Drupal template, so that we can use some update JS code that we want to use going forward.
There should be no functional difference for users and I assume that it's unlikely that we'll be adding more of these widgets in Markdown in the near future.
Related PR: https://github.com/department-of-veterans-affairs/vets-website/pull/10256
> Update widget markup

- pages/change-address.md
url: www.va.gov/change-address
Heroku: https://vagov-content-pr-477.herokuapp.com/change-address
`<button>` is not supported in the WYSIWYG fields in the CMS. 
Change to `<a href>`
Make sure the Sign in link works as expected, at https://vagov-content-pr-477.herokuapp.com/change-address
> Change <button> to <a href> to comply with CMS

- pages/disability/eligibility/former-pows.md
url: https://www.va.gov/disability/eligibility/former-pows/
heroku: https://vagov-content-pr-475.herokuapp.com/disability/eligibility/former-pows/
`<title>` is limited to 70 characters in the CMS, to enforce SEO style guide. the `title` frontmatter for the above URL has 73. 
We need to remove 3 or more characters.
> Shorten <title> for POWs disability benefits

- pages/change-address.md
url: https://www.va.gov/change-address 
heroku, to compare: https://vagov-content-pr-474.herokuapp.com/change-address
There's an extra `| Veterans Affairs` in the `<title>` tag, per screenshot below
Remove ` | Veterans Affairs` from the `title` frontmatter (it get inserted somewhere else).
> Remove extra "| Veterans Affairs" in meta title tag

- pages/education/about-gi-bill-benefits/post-9-11.md
url: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
1. A new section "What is the Location-Based Housing Allowance (Section 107)?" is displayed between the following sections on the page https://www.va.gov/education/about-gi-bill-benefits/post-9-11/ :
- "How can I use my Post-9/11 GI Bill benefits?"
- "Get more information"
2. The section title (What is the Location-Based Housing Allowance (Section 107)?) has an anchor tag so that external links can load the page with the section displayed.
3. The section has the following content:
"What is the Location-Based Housing Allowance (Section 107)?
Previously, GI Bill beneficiaries were paid Monthly Housing Allowance (MHA) based on the main or branch campus of the school they were enrolled. If a student attended classes at more …
> Updated post-9-11.md webpage

- pages/disability/upload-supporting-evidence.md
url: https://www.va.gov/disability/upload-supporting-evidence/
Content bug found during migration. Two Questions are unintentionally nested inside another one.
add `</div>`
> Add missing /div for schema.org/question

- pages/privacy-policy.md
- pages/veterans-portrait-project.md
- pages/welcome-kit.md
url: 
- /privacy-policy/
- /veterans-portrait-project/
- /welcome-kit/
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19169
These pages were missing `hidesidenav: true` in their frontmatter, causing them to render with empty whitespace on the left side. For example -
This PR fixes that by adding `hidesidenav: true` to those pages.
> Fix layout on detail pages not requiring the side nav

- Jenkinsfile
- package.json
N/A
CMS Prod errors cause PRs here to fail. Using the cached CMS data from S3 should resolve this.
The cached CMS data on S3 is used during vets-website builds if the latest data from the CMS results in a build error. vagov-content doesn't have this step, so a fail results in a PR that cannot be merged. This PR fixes that by using the cache.
> Use cached CMS data to do Jenkins build

- fragments/megamenu/index.yml
url: site-wide
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17695
In the MegaMenu, under the Records tab of the VA Benefits and Health Care section, there is a column title that says `Manage your records`. This title should be omitted. This PR removes the title from the config. See image below.
These PR goes alongside the changes in this vets-website PR, https://github.com/department-of-veterans-affairs/vets-website/pull/10421.
> [MegaMenu] Remove the second column title from the Records section

- pages/education/index.md
url: /education
https://github.com/department-of-veterans-affairs/vagov-content/issues/507
Add "Not a Veteran?" section to right rail
> [Education] Add "Not a Veteran?" section to right rail

- pages/education/about-gi-bill-benefits/post-9-11.md
url: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
Malformed schema.org markup
https://vagov-content-pr-514.herokuapp.com/education/about-gi-bill-benefits/post-9-11/ should look the same as https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
> Fix schema.org markup on 9/11 GI bill page.

- pages/disability/file-an-appeal/board-of-veterans-appeals.md
For https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/
url: https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/
Migration script is choking on FAQs inside <section> tags. 
To reserve the id's (temporarily, they'll change post-migration and we'll have to fix the anchor links again in CMS post-migration), i've moved the id's to the h2s 
There should be no change for end user, just some markup updates.
> Move ids from <section> to <h2> to help with FAQs migrations.

- pages/burials-memorials/veterans-burial-allowance.md
url: https://vagov-content-pr-137.herokuapp.com/burials-memorials/veterans-burial-allowance/
The schema.org/howto includes a ton of QAs, and we think that's causing the migration script to choke. 
I've added two missing `</div>s` where i think they belong
> Add missing </div></div> to help migration script parse the page.

- pages/education/about-gi-bill-benefits/how-to-use-benefits/flight-training.md
url: https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/flight-training/
Bad schema.org markup
Just markup change, should look the same on the front end
Compare URL above to https://vagov-content-pr-515.herokuapp.com/education/about-gi-bill-benefits/how-to-use-benefits/flight-training/
> Fix schema.org markup on flight training page

- pages/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program.md
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/
Stakeholder request, per weekly DSVA-EDU call. 
The VET TEC provider chart needs to be removed from the page. We need to direct users to: https://www.benefits.va.gov/GIBILL/FGIB/VetTecTrainingProviders.asp to see the list of VA-approved training providers.
> Content-removing-VET-TEC-provider-chart

- fragments/megamenu/index.yml
url: site-wide
https://github.com/department-of-veterans-affairs/va.gov-team/issues/729
Update title of About VA link to be clearer that it's an "about us" page
> [MegaMenu] Update title for link to "About VA"

- pages/sign-in-faq.md
url: /sign-in-faq
Discovered deprecated HTML while validating links across site
[Per W3, we should use global IDs instead of anchor names](https://www.w3schools.com/tags/att_a_name.asp)
> The <a> name attribute is not supported in HTML5. Use the id attribute instead.
Those name values appear to only have been used to jump the page to a certain accordion panel on page load. I just moved those name values into IDs of the proper accordion list element and verified that they all the hash values work okay.
> Remove deprecated named anchors from sign-in-faq.md

- .github/CODEOWNERS
This PR updates the GitHub code owners to:
- Stop notifying former team members 😞 (hope you all return)
- Notify FE engineering group when a request to publish a homepage banner comes through.
> Update GitHub code owners config

- fragments/home/banner.yml
We are currently using `'` to wrap the multiline content string. This PR switches that to use a `|` because it's unlikely that a `|` will be needed in the content, reducing the risk of a syntax error.
> [Banner] Change format of multiline string in YML file

- fragments/megamenu/index.yml
url: Any page, since the edit is in the header megamenu.
CMS team / internal
Background: _For quality control, while the Drupal CMS-generated menu is being QA'd and released, the Drupal-generated menu and this menu must match in order for the Drupal menu to be built and published._
Currently, the Records tab of the menu has a 3rd column that, unlike other hub tabs, does not have a header. 
However, Drupal cannot generate a blank menu item. The Drupal menu data structure will not match the current structure.
So, our solution is to re-add the subhead "Manage your records" to both the Drupal menu and the megamenu fragment here. 
Cc @jefflbrauer @andrewlewandowski @mnorthuis
> Add subhead to megaMenu Records tab

- pages/school-administrators.md
url: staging.va.gov/school-administrators/
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19988
a. Text is replaced with: "Training on VA-ONCE newest enhancements, version P059"
b. URL is replaced with: https://www.benefits.va.gov/gibill/docs/vaonce/VAONCE_Training.pdf
> 19988: AC 2, 4, and 5 for 19988

- pages/coronavirus-chatbot.md
url: https://dev.va.gov/coronavirus-chatbot/
Related to this [merged PR](https://github.com/department-of-veterans-affairs/vagov-content/pull/657)
Lock in cdn version instead of using latest
Note: We want to lock to a particular version, in order to have a stable base for testing. If we pull the latest from the CDN, it's possible that a given user will get a new version of the chatbot framework before we've had a chance to test it.
> [#93] Binds cdn version to 4.8.0 instead of latest

- pages/coronavirus-chatbot.md
url: https://dev.va.gov/coronavirus-chatbot/
Related to previous [issue](https://github.com/department-of-veterans-affairs/vagov-content/pull/658) and [department-of-veterans-affairs/covid19-chatbot#93] 
Per this [Slack thread](https://dsva.slack.com/archives/C011BG82ZL6/p1587501919461900), we want to use the gzipped webchat-es5 cdn link because webchat-es5 is IE11 compatible and the compressed version (gzip) brings it down to 700Kb (vs 3.1mb).
> Uses gzipped es5 version (for IE11 compatibility) of latest release cdn for chatbot

- pages/coronavirus-chatbot.md
url: https://dev.va.gov/coronavirus-chatbot/
Related to multiple slack threads about [checkbox text cut off](https://dsva.slack.com/archives/C011BG82ZL6/p1587574398106800) and [checkbox touch target](https://dsva.slack.com/archives/C011BG82ZL6/p1587566592054800)
- Fixes checkbox text being cut off related to this [tracking issue](https://github.com/department-of-veterans-affairs/covid19-chatbot/issues/136)
- Fixes checkbox touch target so not overlapping related to this [tracking issue](https://github.com/department-of-veterans-affairs/covid19-chatbot/issues/86)
**Safari responsive screen**
> Chatbot checkbox fixes

- pages/coronavirus-chatbot.md
url: https://dev.va.gov/coronavirus-chatbot
Additional fix for [[department-of-veterans-affairs/covid19-chatbot#86](https://github.com/department-of-veterans-affairs/covid19-chatbot/issues/86)] 
- Checkboxes are now aligned with the first line of the label text
**Before**
**After**
> Adjusts chatbot checkboxes to be aligned with top of label text

- pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#126] 
- Current solution is manual
- This last updated date should match the date on the [VA.gov coronavirus FAQ page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/)
> Adds last updated date to chatbot 

- pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#126] 
Manually updates date again as it has changed on the FAQ page today
> Updates date from VA coronavirus FAQ page

- pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#147]
[department-of-veterans-affairs/covid19-chatbot#83]
Dropdown text in large font sizes was being covered by the arrow icon. After some discussion with @artsymartha68 @toddstanich @1Copenut, here is our proposed solution:
**Also in this PR, issue 83 was fixed so avatar icons and one-line chatbot responses are better aligned.**
>  Fixes dropdown cutoff in larger font sizes iOS Safari

- pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#98] 
- Yellow focus halo around answer buttons fixed for accessibility purposes
- Other button styles consolidated
**BEFORE**
**AFTER**
> Fixes yellow focus halo for buttons

- pages/coronavirus-chatbot.md
url: https://va.gov/coronavirus-chatbot
[department-of-veterans-affairs/covid19-chatbot#98]
Fixing button cutoff that broke in the previous focus halo fix.
**BEFORE**
**AFTER**
> [department-of-veterans-affairs/covid19-chatbot#98] fixes button cutoff

- pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#112]
Message about timeout added as a note below the larger info text.
> Adds note about timeout above chatbot

- pages/cerner-staging/appointments.md
- pages/cerner-staging/messaging.md
- pages/cerner-staging/prescriptions.md
- pages/cerner-staging/records.md
- pages/cerner-staging/results.md
Does not build to prod
- `/cerner-testing/appointments`
- `/cerner-testing/messaging`
- `/cerner-testing/prescriptions`
- `/cerner-testing/records`
- `/cerner-testing/results`
Test pages for Cerner
> Add Cerner test pages

- pages/vsa/design.md
This PR adds a page that will live at `https://staging.va.gov/vsa/design.html` to help document design patterns and components commonly used across the VSA application portfolio.
> Add page for VSA design

- pages/cerner-staging/index.md
This adds a placeholder file to get rid of the broken link errors we are seeing about the breadcrumbs in the `/cerner-staging/` files.
> Add placeholder file

- pages/vsa/index.md
url: /vsa (staging only)
Slack
Adds a placeholder at `/vsa` so that the broken link checker doesn't keep flagging a broken link in the breadcrumbs of `/vsa/design.html`
> Add placeholder page to stop broken links in staging

- pages/ask-va/index.md
This PR adds a page for non-production environments that can be accessed at https://staging.va.gov/ask-va to test the new `ask-va` link widget:
> Add ask va test widget page

- pages/school-administrators.md
Reverts department-of-veterans-affairs/vagov-content#875
This change caused the page to look like this
> Revert "Update school-administrators.md"

- pages/school-administrators.md
Closes [#211](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/211) by adding the "upload a document" feature.
Closes [#231](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/231) by removing the "keywords" section.
**Screenshot:**
> 211/231 - Remove "keywords" / add "upload a document" feature

- pages/404.md
url: any 404 page
https://dsva.slack.com/archives/CBU0KDSB1/p1704994672158839
Regression on the global 404 page was discovered. It was referencing one-off styles that were removed from Formation. The markup has been updated to use classes available in the design system.
The content-build template that is included on this page (`{% include "src/site/includes/common-and-popular.html" %}`) has also been updated in this PR: https://github.com/department-of-veterans-affairs/content-build/pull/1864
> update 404 page styles to use current DS styles

- pages/school-administrators.md
Closes [#226](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/226)
Updates the breadcrumb text from "School administrators" to "Resources for schools"
Screenshot:
> 226 - Update breadcrumb text

- pages/school-administrators.md
Closes[ #210](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/210)
Adds a section to the accordion in the side bar for the newsletter.
Screenshot:
Notes:
- The URL (https://public.govdelivery.com/accounts/USVAVBA/subscribers/qualify) given in the ticket renders an error message, so I modified that to this: https://public.govdelivery.com/accounts/USVAVBA/subscriber/new
- In the design the icon next to the link is vertically centered, even when the text flows to multiple lines. That's not how the design system works. I left comments on the ticket about this.
- In the data I've indicated that this link is not "external" which should cause the link to open in the same window/tab, but that feature appears to be broken. We'll …
> Newsletter link

- pages/school-administrators.md
Closes [#334](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/334)
Removes `<br>` elements which were used for presentational purposes rather than semantic ones. To retain desired spacing, CSS classes and components are used instead.
I also found this to be a good opportunity to remove `<b>` elements for the same reason. The apparent usage was presentational, to make the text bold. That's not what the bold element is for, [beginning with HTML 5](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-b-element).
---
---
---
> Remove HTML breaks in favor of CSS classes and components

- pages/school-administrators.md
Closes [#367](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/367)
All links are intended to open in the same tab, so this change removes metadata specifying that some links should open in a new tab—lines like this: `external: true`.
Additionally, a [bug fix](https://github.com/department-of-veterans-affairs/content-build/pull/1903) means that it will no longer necessary to explicate that a link should open in the same tab, as that will be the default behavior. For that reason, an instance of `external: false` is also being removed. Whether or not that bug fix is merged, this PR should be safe to merge, as currently, the values of `external` have no bearing on the outcome; all links are errantly opening in a new tab.
> Resources for Schools - Open links in the same tab

- pages/school-administrators.md
Closes [#373](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/373)
Overhauls the "Trainings" section:
- New title
- Updated jump link to match new title
- Removed old content in favor of new links and descriptions
- Improved indention in this section
Screenshot:
> Update Trainings and Webinars

- pages/school-administrators.md
Closes [#420](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/420)
Revises the "Trainings and webinars" section with the latest approved content.
**Screenshot:**
> Rrevise "Trainings and webinars" section

- pages/school-administrators.md
Closes [#453](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/453)
Removes the "download" icon for links that are files.
Fixes a typo
**Screenshot showing no download icons, but information about the file is retained:**
> Remove download icons

- pages/school-administrators.md
url: https://www.va.gov/school-administrators/
Kate Caruso via email 8/5/24
Update the link for _Enrollment Manager FAQs_ to redirect to the most recent information
url: https://vbatraining.adobeconnect.com/ptgxzsnw11w7/default/index.html
> Update URL for 'Enrollment Manager FAQs'

- pages/404.md
url: any 404 page redirect
The `.feature` Formation class is deprecated in favor of the va-summary-box web component component.
In the case of the 404 not found pages though, that class is just being used as the background for the search input. To replicate that treatment, this PR will just replace the .feature class with [utility classes](https://design.va.gov/foundation/utilities/).
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2338
I tested this update in staging in the browser by removing the .feature class and adding the utility classes from the inspection screen. There were no visual differences.
> 404 Page: replace .feature with utility classes

- .github/workflows/install/action.yml
url: none
- [related issue](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/2045)
Actions are [failing](https://github.com/department-of-veterans-affairs/vagov-content/actions/runs/14710053112/job/41279879250?pr=943). This was discovered while updating [maintenance.md](https://github.com/department-of-veterans-affairs/vagov-content/pull/943)
> fix(github-actions): update cache action to v4
