department-of-veterans-affairs/vagov-content

pages/disability-benefits/apply/form-526-all-claims.md
Like it says on the tin, this PR adds the 526 all-claims page. This was originally done in vets-website, but according to @ncksllvn, [it happened too little too late.](https://github.com/department-of-veterans-affairs/vets-website/pull/8871#issuecomment-433212956) :man_shrugging:
=> Add 526 all-claims

pages/privacy.md
These two links need to open in a new tab. https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/13946
Checked locally
=> Update links on privacy page

Jenkinsfile
The purpose of the Jenkinsfile in vagov-content will simply be to trigger the vets-website pipeline. vets-websites pipeline will have the logic to handle content only changes.
relates to department-of-veterans-affairs/vets.gov-team/issues/14457
=> [WIP] update Jenkinsfile

pages/records/get-veteran-id-cards/apply.md
Adds VIC V1 page to content repo. 
Issue: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14748
=> add static page for vic react app

pages/records/get-veteran-id-cards/apply.md
=> fix broken link in bread crumb

pages/connected-accounts/index.md
⚠️This pull request is a (pending) dependency for a new app for authorized/connected accounts on VA.gov. It is part of the work that the VA API Platform team is doing around adding Veteran Verification OAuth as a service to End Users.
Ref https://github.com/department-of-veterans-affairs/vets-contrib/issues/178
=> Adding Markdown file for adding Connected Accounts page.

pages/education/survivor-dependent-benefits.md
This is a quick update for ticket 13413. Just a text change.
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13413
=> update for ticket 13413

fragments/home/news.yml
Reverts department-of-veterans-affairs/vagov-content#79
=> Revert "Added exclamation point to story one."

pages/pension/veterans-pension-rates.md
Moves to validate - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14366
=> Add aliases property to catch /pension/rates/

Jenkinsfile
Disabled until we can implement a flag indicating content deploy.
=> Disable the Content Deployment

pages/find-locations/index.md, pages/my-va/index.md, redirects/vets-gov-to-va-gov.yml
Add missing aliases and another redirect for the dashboard
=> Add aliases and another redirect

pages/housing-assistance/home-loans/how-to-apply.md
This PR changes the behavior of the "How To Apply" eBenefits link to open in a new tab.
Sibling content PR to [#8878](https://github.com/department-of-veterans-affairs/vets-website/pull/8878) to resolve [#14530](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14350)
=> Open eBenefits link in new tab

pages/logout.md
Clear localStorage as well to support session cookie authentication.
=> Clear both temporary storages after logout.

pages/records/get-veteran-id-cards.md
Moved some content within the accordions into an ordered list to improve readability.
=> Update to layout in accordions

app.json, fragments/home/news.yml, pages/careers-employment/index.md
Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14959
=> Fix for hardcoded link to localhost

redirects/vets-gov-to-va-gov.yml
Related to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13635
Makes some updates to the redirect list to handle above issues.
=> Redirect fixes

redirects/vets-gov-to-va-gov.yml
I found these looking at GA for pages with our 404 page title.
=> Fix a couple redirects

pages/health-care/health-needs-conditions/mental-health.md
I couldn't replicate this exactly as described in the ticket, but I think this resolves it.
Move to validate - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14993
=> Fix for PDF loading without HTTPS

pages/records/get-veteran-id-cards.md
Per stakeholder feedback we need to remove about the Choice Card being a *photo* ID and that it can be used to get retail discounts.
=> Content-WIP-update VA Choice Card 

pages/careers-employment/vocational-rehabilitation/ides.md
Fix broken collection found using the broken collection script
```
Error: Your [ collection "vreServiceEligibility" ] does not exist in the collection: careers-employment/vocational-rehabilitation/ides/index.html
```
=> fix for broken collections

pages/sign-in-faq.md
url: https://www.va.gov/sign-in-faq/
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15202
Update copy for link to report sign in issue to make it more clear that it is specifically for sign in issues, not all all issues.
=> Update copy for sign in problems link to make it more clear

fragments/home/news.yml
=> Update elderly Vet being examined link label on home page

pages/education/submit-school-feedback.md
url: www.va.gov/education/submit-school-feedback
- release of school feedback tool
- this flag is currently deprecated and the tool is on production behind a password. removing this front matter config so it doesn't get converted in a round of refactoring.
=> remove production false flag

pages/health-care/eligibility.md, pages/health-care/how-to-apply.md
url: https://vagov-content-pr-167.herokuapp.com/health-care/how-to-apply/ and https://vagov-content-pr-167.herokuapp.com/health-care/eligibility/
Stakeholder request to add in Spanish language 10-10EZ.
Addition of helper text and link to Spanish language 10-10EZ, translated into Spanish.
=> adding spanish language helper text

pages/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas.md
https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas/
CURF request from VBA stakeholder
Update contact information for the Korea BDD office
=> CURF-update-how-to-file-claim-overseas

pages/health-care/view-test-and-lab-results.md
url: https://www.va.gov/health-care/view-test-and-lab-results/
User research: One participant was confused by "Labs + Tests" and "lab and test results"
Minor tweaks for clarity
=> updates based on user research

pages/disability/va-claim-exam.md
https://www.va.gov/disability/va-claim-exam/ 
CURF request from VBA stakeholder 
Update content about what Veterans should bring to a VA claim exam.
=> content-WIP-VA-claim-exam-update

pages/education/after-you-apply.md
url: https://www.va.gov/education/after-you-apply/
Noticed a typo.
Fix the spelling.
=> Fix on after-you-apply page

pages/disability-benefits/apply/form-526-all-claims.md
url: `disability-benefits/apply/form-526-all-claims`
Internal
Need to enable the app in production. It'll be behind a password when the corresponding devops PR gets merged.
The devops PR needs to be merged and deployed before this gets merged.
=> Enable all claims in production

pages/health-care/about-affordable-care-act.md
url: https://www.va.gov/health-care/about-affordable-care-act/
Change in law
Updates to reflect repeal of individual mandate for plans starting in 2019
=> Content wip aca updates

pages/health-care/about-va-health-benefits/dental-care.md
url: https://www.va.gov/health-care/about-va-health-benefits/dental-care/
Stakeholder
Revise language in first accordion.
=> Update dental-care HC page per stakeholder

pages/my-va/find-benefits/index.md, pages/my-va/index.md
=> Add preferences breadcrumbs

pages/disability/after-you-file-claim.md, pages/disability/how-to-file-claim.md, pages/housing-assistance/home-loans/how-to-apply.md
urls: 
https://www.va.gov/housing-assistance/home-loans/how-to-apply/
Stakeholder through our content update request form
Change one word on the home loans how to apply page.
Change number of days and month on two disability pages.
=> content/wip/Update Requests: revisions to 3 pages

pages/health-care/health-records/index.md
The Health Records app (`/health-care/health-records/`) has been retired, so this page can be safely removed.
`https://www.vets.gov/health-care/health-records` redirects to `https://www.va.gov/health-care/get-medical-records/`.
=> Remove Health Records app

pages/logout.md
This only affects the script in the logout page at the end of the logout flow.
The rest of the FE changes are here: department-of-veterans-affairs/vets-website#9309
=> Logout in same window when full screen login is toggled on.

pages/sign-in-faq.md
url: https://www.va.gov/sign-in-faq/
Call center is getting a high volume of calls around sign-in issues.
FAQ providing first-line tips for dealing with sign-in issues.
=> adding question re: sign in issues

fragments/home/banner.yml
=> Updating text for the alert banner

README.md
=> Update README in prep for training demo

pages/housing-assistance/index.md
url: https://www.va.gov/housing-assistance/
Home Loan SME
Need to add link to non-Veteran audience home loan information.
=> adding non-vet audience callout hub

pages/my-va/find-benefits/index.md, pages/my-va/index.md
Will use the Breadcrumbs component instead
This related PR should be merged at the same time: https://github.com/department-of-veterans-affairs/vets-website/pull/9424
url:
=> Remove static breadcrumbs from content

pages/account/connected-accounts/index.md
url: /account/connected-accounts/
As part of pregolive checklist https://github.com/department-of-veterans-affairs/vets-external-teams/blob/master/DeveloperDocs/testing/cross-browser-manual-testing.md I'm working on crossbrowser testing
Access the feature in staging
=> Release the connected accounts to staging

fragments/home/banner.yml
Hey Team
We got this from the White House at 10pm last night I guess. I am sorry about the weekend request but this needs to be pushed out ASAP.
url:
=> Removing Alert Banner

pages/disability/how-to-file-claim/evidence-needed/fully-developed-claims.md
https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims/
Stakeholder request to update the Disability FDC page with all 5103 information.
Need to add more 5103 information to the current Disability FDC page to include all situations in which a Veteran might need to file additional forms or evidence for their disability claim.
=> Content-WIP-disability-FDC-5103-info

pages/disability/after-you-file-claim.md, pages/disability/how-to-file-claim.md
CURF request to update January disability claims processing time
=> Content-WIP-CURF-Disability-January-claims-time

pages/disability-benefits/apply/form-526-all-claims.md
url: `/disability-benefits/apply/form-526-all-claims/*`
Linked ticket
Updated the name of the form in the breadcrumb to match the form title we show people on the intro page.
=> Update breadcrumb to match the form title that's on the intro page

pages/beta-enrollment/all-claims.md
url: beta-enrollment/all-claims
internal/stakeholder
Adding entry page for all claims beta-enrollment to facilitate beta testing
=> Add beta entry page for all claims (526 V2)

pages/burials-memorials/veterans-burial-allowance.md, pages/claim-or-appeal-status.md, pages/disability/eligibility.md, pages/disability/how-to-file-claim.md, pages/education/bak_index.md, pages/education/eligibility.md, pages/education/how-to-apply.md, pages/education/opt-out-information-sharing.md, pages/health-care/eligibility.md, pages/health-care/get-medical-records.md, pages/health-care/how-to-apply.md, pages/health-care/refill-track-prescriptions/index.md, pages/health-care/schedule-view-va-appointments.md, pages/health-care/secure-messaging.md, pages/health-care/view-test-and-lab-results.md, pages/pension/eligibility.md, pages/pension/how-to-apply.md, pages/records/download-va-letters.md, pages/records/get-veteran-id-cards/vic.md
As part of the CMS work, we're going to move to connecting widgets through an attribute, instead of having a list of hardcoded urls. This updates the existing static content with these widget types, so that we can switch over now.
Related PR: https://github.com/department-of-veterans-affairs/vets-website/pull/9582.
None of these changes are breaking changes, they're only additive.
=> Add widget types to static widgets

pages/pension/eligibility.md
Missed one type in my last PR for these.
=> Fix widget type on pension page

pages/disability/how-to-file-claim.md, pages/disability/how-to-file-claim/evidence-needed/fully-developed-claims.md, pages/disability/how-to-file-claim/when-to-file.md
CURF request from Misty Sweet. 
Per stakeholder we need to replace "Reopened Claim" with "Supplemental Claim"
update this content: 
Reopened claim – a claim providing new evidence to support a disability claim that was denied at least 1 year ago.
With this content: 
Supplemental Claim – a claim providing new evidence to support a disability claim that was denied.
=> CURF-request-reopened claim update

fragments/home/cards.yml, fragments/home/hubs.yml, fragments/home/news.yml
=> Sentence Casing 

pages/account/connected-accounts/index.md
url: https://www.va.gov/account/connected-accounts
@patrickvinograd asked me to turn on page for UAT Production testing with Veterans including myself.
Turning page on so that we can do testing with veterans, we've already testing in staging and code does work as expected.
=> Turning on Connected Accounts in Production

pages/careers-employment/index.md, pages/careers-employment/va-transition-assistance.md
url: https://www.va.gov/careers-employment/
validating ticket #14446
=> Content wip transition assistance bug

pages/dst/index.md
Internal, testing Content
Changing some copy
=> Updating content on decision support tool stage page

pages/disability/after-you-file-claim.md, pages/disability/how-to-file-claim.md
CURF request from stakeholder
Update disability claim processing time for February to 125.7 days
=> CURF-request-update-disability-claim-time-february

pages/dst/index.md
internal, testing out some CORS and js  between client and server side
=> Testing some CORS and ajax request

pages/dst/index.md
Problems calling http address from VA premises. Changing url to TLS-backed.
=> Asset loading problems, changing source

pages/dst/index.md
Fork of @a12k's changes to https://github.com/department-of-veterans-affairs/vagov-content/blob/a12k-s3-assets/pages/dst/index.md to update copy and the name of the DST tool to make it more Veteran-friendly. I think I kept everything in separate commits so you can 🍒-pick what you want if necessary.
=> DST copy updates

pages/dst/index.md
Spoke with James K, suggested changing the link to the s3 bucket holding jquery.
=> Changing source of jquery asset

pages/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994.md
url: https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994
Must be merged after [this](https://github.com/department-of-veterans-affairs/devops/pull/4237) PR is merged and revproxy deploy.
=> DO NOT MERGE- remove from production exclusion list

pages/dst/index.md
url: stating.va.gov/dst
Just changed an asset url
=> Change source of js asset

pages/dst/index.md
Add va-prod loading gif, remove intro paragraph upon return.
url:
=> Some styling changes

pages/health-care/health-needs-conditions/mental-health.md
url: /health-care/health-needs-conditions/mental-health/
See ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16951
Add blue banner to top of page -
=> Add banner to Mental Health

pages/dst/index.md
We originally were discussing adding copy about grandfather status, but for purposes of this example tool we'll keep it general and talk about the personal needs of the Veteran.
cc @a12k
=> Tweak copy about contacting primary care physician in eligibility results

pages/dst/index.md
=> styling copy changes

pages/dst/index.md
=> Update for feature styling

pages/health-care/health-needs-conditions.md, pages/health-care/health-needs-conditions/chemical-hazardous-materials-exposure.md, pages/health-care/health-needs-conditions/health-topics-a-z.md, pages/health-care/health-needs-conditions/mental-health.md, pages/health-care/health-needs-conditions/military-sexual-trauma.md, pages/health-care/health-needs-conditions/substance-use-problems.md, pages/health-care/health-needs-conditions/womens-health-needs.md
url: Health Needs and Conditions
See ticket
Ticket - department-of-veterans-affairs/vets.gov-team/16927
=> Rearrange items in Health Needs and Conditions sidebar

pages/burials-memorials/index.md
We need to update the facebook burials link on: https://www.va.gov/burials-memorials/
TO: https://www.facebook.com/NationalCemeteries/
CURF stakeholder request
=> CURF-request-update-burials-facebook-link

pages/pension/aid-attendance-housebound.md, pages/pension/eligibility.md, pages/pension/how-to-apply.md, pages/pension/pension-management-centers.md, pages/pension/survivors-pension-rates.md, pages/pension/survivors-pension.md, pages/pension/veterans-pension-rates.md, pages/va-payment-history.md
Pension parity edits
Assess and implement changes to bring parity between new VA.gov pages and legacy VA.gov pages in the Pensions section.
=> Content-WIP-pension-parity-edits

pages/disability/eligibility/special-claims/clothing-allowance.md
url: https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/
Rate change
Change current clothing allowance rate
=> updating rate

.github/CODEOWNERS, Jenkinsfile, fragments/home/banner.yml
This PR adds a Jenkins step so that when a PR is opened that modifies the homepage, we receive a Slack notification in our oncall channel.
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16883
=> Add a Jenkins step for alerting changes to homepage

pages/disability/file-for-increased.md
url:  https://staging.va.gov/disability/how-to-file-claim/
Updates sidebar link for 526
=> Link update for 526

pages/dst/index.md
Sending status content from the app server to post on the frontend, rather than hardcoding content.
Currently the response content is hardcoded into the html. Moving the content to the app server to more dynamically generate a response based on entered parameters, rather than using generic responses.
=> Un-hardcoding content from the html

Jenkinsfile
@wyattwalter @wunderhund @omgitsbillryan for awareness
=> Limit scope of homepage alert to just banner and news

pages/health-care/schedule-view-va-appointments.md
url: https://www.va.gov/health-care/schedule-view-va-appointments/
developer: CMS Migration
The migration script expects alerts with the same name (heading) to be identical across all of the pages where it is used. On other pages, the "How do I talk to someone right now?" alert uses dashes in its phone link. This PR adds dashes to the link to make it consistent with the others.
This PR should not change the page's content or appearance or the behavior of the link.
=> Add dashes to "tel:" link for consistency with other alerts.

pages/health-care/about-va-health-benefits.md, pages/health-care/after-you-apply.md, pages/health-care/eligibility.md, pages/health-care/family-caregiver-benefits/champva.md, pages/health-care/get-medical-records.md, pages/health-care/health-needs-conditions/mental-health.md, pages/health-care/how-to-apply.md, pages/health-care/index.md, pages/health-care/order-hearing-aid-batteries-prosthetic-socks.md, pages/health-care/refill-track-prescriptions/index.md, pages/health-care/schedule-view-va-appointments.md
Originated from https://github.com/department-of-veterans-affairs/vagov-content/pull/332
=> Change all <b> tags to <strong> tags. (#332)

pages/health-care/health-needs-conditions/mental-health.md, pages/health-care/health-needs-conditions/mental-health/depression.md, pages/health-care/health-needs-conditions/mental-health/ptsd.md, pages/health-care/health-needs-conditions/mental-health/suicide-prevention.md, pages/health-care/health-needs-conditions/military-sexual-trauma.md, pages/health-care/health-needs-conditions/substance-use-problems.md
url: 
/health-care/health-needs-conditions/mental-health/
/health-needs-conditions/mental-health/ptsd/
/health-care/health-needs-conditions/mental-health/depression/
/health-care/health-needs-conditions/mental-health/suicide-prevention/
/health-care/health-needs-conditions/military-sexual-trauma/
/health-care/health-needs-conditions/substance-use-problems/
Internal
The purpose of this PR is to add dataLayer events to track clicks on for mental health EO on the above-listed pages.
=> [Analytics] Track clicks for Mental Health EO

Jenkinsfile, fragments/home/banner.yml
Should scope the alert trigger better, so that adding new hubs doesn't keep triggering the oncall channel.
Will also add the PR number into the link per https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17526.
=> [Jenkinsfile] Tweak homepage alert

pages/service-member-benefits.md
=> fixing top 3

fragments/megamenu/index.yml
top nav cap fix
bug fix
cap the L in Location
=> content/wip/cap the L in Find a VA location top nav

pages/education/compare-education-benefits.md
url: `/education/about-gi-bill-benefits/`
Internal (@mnorthuis)
This PR fixes the broken link on **Compare Education Resources** link within the side nav.
=> [Broken Link] Update Education Side Nav

pages/veteran-representative/index.md
Adds a feature flag to remove `/veteran-representative/` from prod.
=> Remove Veteran Representative from Prod

pages/burials-memorials/index.md, pages/careers-employment/index.md, pages/disability/index.md, pages/education/index.md, pages/family-member-benefits.md, pages/health-care/index.md, pages/housing-assistance/index.md, pages/life-insurance/index.md, pages/pension/index.md, pages/service-member-benefits.md
url: 
```
/service-member-benefits/
/family-member-benefits/
/burials-memorials/
/careers-employment/
/housing-assistance/
/pension/
/life-insurance/
/education/
/records/
/health-care/
/disability/
```
internal
The purpose of this PR was to make the "U" lowercase in "Follow Us" in the sidebar on all hub pages.
This was achieved by first updating the `/src/site/components/merger-social.html` template in `vets-website` repo, then updating the copy in all hub pages `index.md`
**NOTE**: This PR must be merged with [this vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/9840), or else the social icons will break
=> [Hubs] Lowercase the "u" in "Follow Us" in sidebar

pages/disability/after-you-file-claim.md, pages/disability/how-to-file-claim.md
CURF request 
Update disability processing time for March.
=> Update disability process time for March

pages/disability/index.md
url: https://www.va.gov/disability/
Bug
Removing repeated links
=> Removing repeated links within "Manage Benefits"

fragments/home/news.yml
=> Text change is all this is.

pages/change-address.md
url: /change-address
https://dsva.slack.com/archives/C52CL1PKQ/p1554933070020400
Add special HTML class
=> Change Address - fix ID.me link

pages/find-locations/index.md
url: `/find-locations/`
internal: @jenniferlee-dsva 
The purpose of this PR is to edit the following metadata for the Facility Locator:
- **title**: Find VA Locations | Veterans Affairs
- **description**: Find a VA medical center, clinic, hospital, cemetery, or a VA benefits office near you. Search by city, state, ZIP code, or service. Get wait times and directions.
- **keywords**: VA location by zip code, VA clinic, VA near me
**Note**: [This PR](https://github.com/department-of-veterans-affairs/vets-website/pull/9903) captures the work done on `vets-website` repo to accommodate adding `keywords` as a meta property and custom `<title>`
=> Facility Locator: Update Metadata for SEO

pages/account/index.md
Account Settings
url: /account/
Stakeholder: Content Team - Style Guide updates
GH Issue: [11768 Acct Settings LOA3: Style guide updates Implementation](/department-of-veterans-affairs/vets.gov-team/issues/17768)
Just need PR reviewed & approved.  Edit already made: Changed Account Setting page breadcrumb case from title-case to sentence-case.
=> 11768 - Change acct-settings page breadcrumb case.

pages/careers-employment/index.md, pages/disability/eligibility/ptsd.md, pages/family-member-benefits.md, pages/housing-assistance/index.md, pages/service-member-benefits.md
No visible changes, but these -
careers-employment
disability/eligibility/ptsd
family-member-benefits
housing-assistance
service-member-benefits
Bug on master
Add element IDs
=> Add element IDs to each expandable alert banner for accessibility

pages/careers-employment/index.md, pages/disability/eligibility/ptsd.md, pages/family-member-benefits.md, pages/housing-assistance/index.md, pages/service-member-benefits.md
This PR modified the now-standardized expandable alert banners based on https://github.com/department-of-veterans-affairs/vets-website/pull/9961. 
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17777
careers-employment
disability/eligibility/ptsd
family-member-benefits
housing-assistance
service-member-benefits
=> Improvements to expandable alert banners

pages/health-care/my-health-account-validation.md
url: https://va.gov/my-health-account-validation/
Internal
Currently, when authenticated users click the "My Health" link in the main nav, they are automatically redirected to MHV, even if their account is not in the appropriate state to access it.  This newly created page will act as an intermediary that will check their account status, and display any related messaging if they need to take action before being able to access MHV.
=> Add new page for MHV account validation

pages/profile/index.md
UX Team - @Samara-Strauss 
[17767 - Profile Style Guide updates implementation](/department-of-veterans-affairs/vets.gov-team/issues/17767#issuecomment-487105961)
Changed Profile page breadcrumb case from title-case to sentence-case, per Style Guide updates.
=> 17767 - Change Profile page breadcrumb case.

pages/privacy-policy.md, pages/sign-in-faq.md
url: /privacy
Privacy office
Change url and add text link to the privacy office.
`vets-website` changes - https://github.com/department-of-veterans-affairs/vets-website/pull/9973
=> Content-wip-update and rename privacy page

Jenkinsfile, package.json
This PR adds the `--pull-drupal` argument into the command for build the site in Heroku and in Jenkins.
=> Pull latest Drupal for Heroku builds (disable cache)

pages/privacy-policy.md
Ticket - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18269
url: /privacy-policy
Internal
Convert "services" to singular form
=> Remove last "s" from "VA privacy services"

pages/records/download-va-letters.md
url: pages/records/download-va-letters.md
cms migration requirement.
The section tags on the page are causing problems for the migration script. Removing them should have no effect on the appearance or behavior of the page.
=> Remove section tags from 'Download VA Records' to simplify migration.

pages/disability/after-you-file-claim.md, pages/disability/how-to-file-claim.md
Stakeholder request to update disability claim process time 
Update the number of days it takes to process disability claims for April
=> CURF-request-disability-claims-process-time-April

pages/burials-memorials/dependency-indemnity-compensation.md, pages/disability/how-to-file-claim/evidence-needed.md, pages/disability/how-to-file-claim/when-to-file.md, pages/disability/how-to-file-claim/when-to-file/pre-discharge-claim.md, pages/disability/va-claim-exam.md, pages/housing-assistance/home-loans/eligibility.md, pages/housing-assistance/home-loans/how-to-apply.md, pages/life-insurance/options-eligibility/fsgli.md, pages/life-insurance/options-eligibility/vgli.md, pages/pension/how-to-apply/fully-developed-claim.md, pages/sign-in-faq.md
url: Numerous
Drupal won't support aria-multiselectable accordions for Q&A Sections, and most if not all were not intentional. 
Remove all instances of aria-multiselectable
=> Remove all instances of aria-multiselectable=true.

pages/disability/file-an-appeal.md
url: https://www.va.gov/disability/file-an-appeal/
After: https://vagov-content-pr-419.herokuapp.com/disability/file-an-appeal/
During anomaly discovery i found one use of   `<ul class="vertical-list-group more-bottom-cushion"> `where normally it would be an `<ol class="process">`
Change `<ul>` to `<ol>` and update `<li>` classes.
=> Replace unique ul.vertical-list-group with ol.process.

pages/records/download-va-letters.md, pages/records/get-military-service-records.md, pages/records/get-veteran-id-cards.md, pages/records/get-veteran-id-cards/vic.md, pages/records/index.md
url: 
https://www.va.gov/records/get-veteran-id-cards/
https://www.va.gov/records/get-military-service-records/
https://www.va.gov/records/download-va-letters/
https://www.va.gov/records/get-veteran-id-cards/vic/
https://www.va.gov/records/
https://vagov-content-pr-422.herokuapp.com/records/get-veteran-id-cards/records/get-veteran-id-cards/
https://vagov-content-pr-422.herokuapp.com/records/get-veteran-id-cards/records/get-military-service-records/
https://vagov-content-pr-422.herokuapp.com/records/get-veteran-id-cards/records/download-va-letters/
https://vagov-content-pr-422.herokuapp.com/records/get-veteran-id-cards/records/get-veteran-id-cards/vic/
https://vagov-content-pr-422.herokuapp.com/records/get-veteran-id-cards/records/
If "lastupdate" is empty, the CMS will display Jan 1 1970. …
=> Add lastupdate frontmatter for records.

pages/logout.md, pages/session-expired.md
Also added the associated GA event.
> ![Screenshot_2019-05-03 Session Expired](https://user-images.githubusercontent.com/1067024/57130187-ba3a8580-6d66-11e9-85c7-bac3cd3b9b78.png)
=> Updated copy for session expired page

pages/disability/file-an-appeal/request-priority-review.md
url: https://www.va.gov/disability/file-an-appeal/request-priority-review/
Stakeholder
Change phone number and fax number.
=> update phone and fax numbers: request priority review

pages/records/get-veteran-id-cards.md
url: /records/get-veteran-id-cards
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/14432
Update the link to form 1172-2
=> Update link to 1172-2

pages/change-direct-deposit-and-contact-information.md, pages/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships.md, pages/education/about-gi-bill-benefits/how-to-use-benefits/test-fees.md, pages/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up.md, pages/education/about-gi-bill-benefits/how-to-use-benefits/tutor-assistance.md, pages/education/about-gi-bill-benefits/how-to-use-benefits/work-study.md, pages/education/about-gi-bill-benefits/montgomery-active-duty/buy-up.md, pages/education/about-gi-bill-benefits/montgomery-selected-reserve.md, pages/education/about-gi-bill-benefits/post-9-11.md, pages/education/change-gi-bill-benefits.md, pages/education/choosing-a-school.md, pages/education/other-va-education-benefits/national-call-to-service-program.md, pages/education/other-va-education-benefits/veap.md, pages/education/survivor-dependent-benefits/fry-scholarship.md, pages/education/transfer-post-9-11-gi-bill-benefits.md, pages/life-insurance/file-appeal-for-tsgli.md, pages/life-insurance/options-eligibility/fsgli.md, pages/life-insurance/options-eligibility/s-dvi.md, pages/life-insurance/options-eligibility/sgli.md, pages/life-insurance/options-eligibility/tsgli.md, pages/life-insurance/options-eligibility/vgli.md, pages/life-insurance/options-eligibility/vmli.md, pages/life-insurance/totally-disabled-or-terminally-ill.md, pages/pension/aid-attendance-housebound.md, pages/pension/how-to-apply.md, pages/pension/survivors-pension.md, pages/records/get-military-service-records.md, pages/records/get-veteran-id-cards.md
url: all pages in Education, Pension, and Life Insurance
Jen Lee, style guide updates
Implement new style guide entries about adding (PDF) at the end of text links that take the user to a PDF and (video) at the end of text links that take the user to a video to watch.
=> content-wip-Implement style guide decisions for PDF and video links

pages/disability/eligibility/hazardous-materials-exposure/agent-orange/vietnam-waters.md
url: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/vietnam-waters/
stakeholder, Misty Sweet
Fix H1: add "Water"
=> content-wip-Update vietnam-waters.md

pages/records/get-veteran-id-cards.md
This was previous done here, https://github.com/department-of-veterans-affairs/vagov-content/pull/437, but then it was overwritten by a subsequent PR, https://github.com/department-of-veterans-affairs/vagov-content/pull/432. However, the former had the correct update.
=> Update link to "Getting your ID card"

pages/careers-employment/vocational-rehabilitation/how-to-apply.md
https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/ 
Need to fix some content anomaly before hub is migrated into Drupal
Remove div.feature blue box and make content normal body copy 
Fix nested question headers
=> Content-wip-careers-anomaly-fix

fragments/home/banner.yml
url: homepage
#oncall channel
Banner on homepage
=> [Homepage] Add banner about severe outage

pages/disability/eligibility/hazardous-materials-exposure/agent-orange/vietnam-waters.md, pages/privacy-policy.md, pages/welcome-kit.md
https://www.va.gov/welcome-kit/
https://www.va.gov/privacy-policy/
We need to fix anomalies on the above pages before content migration to Drupal
1. make this text normal body copy (i.e., not in big intro text font); 
Feel free to share this guide with friends or family members who need help with their benefits too. 
2. Download your VA Welcome Kit and print out copies for yourself and others:
update text links per current style guide. 
Download your VA Welcome Kit in black and white.
Download your VA Welcome Kit in color.
(This is an h2/h3 issue, no impact on migration at this point.) TOC  jump links jump to H3s. They should jump to H2s
=> Content-WIP-Root-anomaly fix

pages/disability/eligibility/hazardous-materials-exposure/agent-orange/vietnam-waters.md
url: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/vietnam-waters/
Misty Sweet
Remove link going to the ships list.
=> content-wip-Update vietnam-waters

Jenkinsfile
Making this value consistent with vets-website, https://github.com/department-of-veterans-affairs/vets-website/blob/a9164d2fb54ce27d9e01967568fbea4d19ca1a01/jenkins/common.groovy#L10.
=> Update address of CMS 

fragments/promotions/health-care.yml
mission act promo in health care mega menu
mission act
update promo to feature mission act
=> updating promo to feature mission act

pages/session-expired.md
Updating the copy of title on session expiration page
Verified locally
=> updating session-exp title

pages/dashboard2/index.md
Corresponding PR that adds the new React app under the new entryname: https://github.com/department-of-veterans-affairs/vets-website/pull/10232
=> Add new app so we can do UAT of Dashboard changes on prod

pages/change-direct-deposit-beta.md
url: /change-direct-deposit-beta
[18503](/department-of-veterans-affairs/vets.gov-team/issues/18503) - Create dynamic CTA for Direct Deposit.
App ID in this page's cta-widget tag is being changed to a new value -- 18503 requires a new “direct-deposit” app-id for our cta-widget component in vets-website.
=> 18503 - Change Direct Deposit beta-page dynamic cta-widget app-id prop.

pages/disability/eligibility/hazardous-materials-exposure/agent-orange/registry-health-exam.md, pages/disability/eligibility/hazardous-materials-exposure/agent-orange/service-outside-vietnam-korea.md, pages/disability/eligibility/hazardous-materials-exposure/agent-orange/vietnam-waters.md, pages/disability/file-an-appeal/request-priority-review.md
url: https://www.va.gov/disability/file-an-appeal/request-priority-review/
Stakeholder: Marcella Coyne
Update the phone number and the fax number.
=> content/wip/fix phone and fax in request-priority-review

pages/careers-employment/vocational-rehabilitation/programs/self-employment.md
url: https://www.va.gov/careers-employment/veteran-owned-business-support/
Anomaly fix.
Add text and a link to the Veteran-owned small business page on the VR&E Self-Employment track page.
=> content/wip/Update self-employment

pages/dashboard2/index.md
=> remove `dashboard2` route that was used for Dashboard UAT

pages/housing-assistance/home-loans/how-to-apply.md
url: https://www.va.gov/housing-assistance/home-loans/how-to-apply/
`<title>` is too long.
Shorten it! From "How To Apply For A VA Home Loan Certificate Of Eligibility" to "How To Apply For A VA Home Loan COE" (per @jenniferlee-dsva)
=> Reduce characters for COE <title> tag

pages/careers-employment/family-resources.md
url: https://www.va.gov/careers-employment/family-resources/
(Compare to the URL from the deployment here: https://vagov-content-pr-472.herokuapp.com/careers-employment/family-resources/)
This page uses the wrong template (i think), so it's not migrating correctly.
=> Change "Family resources" template from topic-landing to detail-page

pages/disability/after-you-file-claim.md, pages/disability/how-to-file-claim.md
url: Disability: How to file a claim **and** After you file your claim
Monthly update to # of days to process claim
Change # of days to 104.1, and change month to June
=> Content disability monthly request

pages/education/about-gi-bill-benefits/post-9-11.md
url: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
As a veteran, I need information provided regarding Location-Based Housing Allowance so that I understand the impact of changes to my GI Bill benefits
The text of the section is updated to match the bold & italic stylings below:
**What is Section 107 (Location-Based Housing Allowance)?**
Previously, GI Bill beneficiaries were paid Monthly Housing Allowance (MHA) based on the main or branch campus of the school they were enrolled. If a student attended classes at more than one location, they were paid the rate that was most advantageous.
Now, MHA is based on the campus location **where the student physically attends the majority of his or her classes.**
VA’s campus definitions:
- **Main campus:** A location where the …
=> update 107 question text to match bold and italic requirements

pages/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam.md, pages/disability/eligibility/hazardous-materials-exposure/agent-orange/service-in-vietnam-korea.md
=> Content agent orange link fixes

pages/housing-assistance/home-loans.md
url: https://www.va.gov/housing-assistance/home-loans/
Content bug identified.
Sentence case a left nav label.
=> Content/wip/Update home-loans

pages/disability/eligibility/ptsd.md
url: /disability/eligibility/ptsd/
Found while on call
Update HTML of additional info to align w/new HTML
=> Fix for toggle in additional info

pages/careers-employment/vocational-rehabilitation/eligibility.md
url: https://www.va.gov/careers-employment/vocational-rehabilitation/eligibility/
Misty Sweet, stakeholder
Remove this sentence: "The sunset date of that law has been extended to September 30, 2018, through Sec. 724 of Public Law 113-291."
=> content-wip-VRE-eligibility-CURF

fragments/megamenu/index.yml
site-wide
Slack
Change link in MegaMenu
=> [MegaMenu] Update link for "VA open data"

package.json
This PR modifies the Heroku startup command to properly import Drupal content from S3 into the website build.
=> [Heroku review instances] Try pulling cached CMS content

fragments/megamenu/index.yml
url: site-wide 
[Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1563828557007400)
Open link in same tab
=> [MegaMenu] Open "Open data" link in same tab

pages/education/how-to-apply.md
url: https://www.va.gov/education/how-to-apply/
Bad schema.org markup
Fix divs.
=> Fix schema.org markup in Education - How to Apply

pages/disability/how-to-file-claim.md
Anomaly fix (removing blue box) for Disability hub
=> Disability anomaly fix

pages/disability/after-you-file-claim.md, pages/disability/eligibility.md, pages/disability/how-to-file-claim.md
Stakeholder request to update disability claim processing time for July. (Jotform request)
Change to: 
109
Average number of days to complete disability-related claims in July 2019
=> Content wip disability process time july update

pages/disability/eligibility.md
https://www.va.gov/disability/eligibility/
url: https://www.va.gov/disability/eligibility/
Migration anomaly for FAQ section
=> Change h4 to h3 to fix anomaly in FAQ section.

pages/disability/eligibility/special-claims/birth-defects.md
url: 
https://www.va.gov/disability/eligibility/special-claims/birth-defects/
Stakeholder request (Misty) to update how to apply for Spina bifida
=> Content-update-spina-bifida-page

pages/decision-reviews/get-help.html, pages/sign-in-faq.md
I encountered a couple 508 problems while working through the PR at https://github.com/department-of-veterans-affairs/vets-website/pull/10541.
=> [508] Fix a couple accessibility issues

pages/disability/eligibility/special-claims/dental-care.md
url: 
https://www.va.gov/disability/eligibility/special-claims/dental-care/
During CMS migration Q/A, the CMS team found broken link on Dental Care page.
=> Content-fix-broken-link-dental-care

pages/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program.md
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/
During CMS Q/A, team identified a content anomaly on Vet Tec page...  text is above eligibility blue box. We need to move text above blue box to below (or integrate it into intro)
=> Content-vet-tec-anomaly-fix

fragments/home/banner.yml
All
I have added the approved language for the national alert for Hurricane Dorian. I wanted to have a break between the Caribbean healthcare info and the Sunshine Healthcare info. I wasn't sure if I should use <br> tags or just hit return. Anyways I went with hitting return. If <br> is the right answer please insert a <br> between the two paragraphs. If you have any questions please call me at 603-339-2269.
Thank you in advance
Josh Tuscher
url:
=> Hurricane Dorian Update

fragments/home/banner.yml
=> All latest Banner Update

fragments/home/banner.yml
All
Please make this update ASAP.
Thank you in advance
Josh Tuscher
url:
=> 8/30 Hurricane Banner Update

pages/burials-memorials/dependency-indemnity-compensation.md
url: https://www.va.gov/burials-memorials/dependency-indemnity-compensation/
Branch: https://github.com/department-of-veterans-affairs/vagov-content/blob/Agent-Orange-Blue-Water-fix/pages/burials-memorials/dependency-indemnity-compensation.md
Heroku: https://vagov-content-pr-535.herokuapp.com/burials-memorials/dependency-indemnity-compensation/
=> Agent orange blue water fix

pages/burials-memorials/dependency-indemnity-compensation.md
url: https://www.va.gov/burials-memorials/dependency-indemnity-compensation/
Branch: https://github.com/department-of-veterans-affairs/vagov-content/blob/Agent-Orange-Blue-Water-fix/pages/burials-memorials/dependency-indemnity-compensation.md
Heroku: https://vagov-content-pr-535.herokuapp.com/burials-memorials/dependency-indemnity-compensation/
Stakeholder request to update information
Addition of alert box about Agent Orange Blue Water coverage
Fix to headline in alert box
=> Update Navy Blue Water alert headline

fragments/home/banner.yml
Updates the YML comment about the multiline delimiter.
=> [Banner] Update YML comment

fragments/home/banner.yml
Hey @ncksllvn 
There was a banner update after all today. Please let me know if you need anything else.
url:
=> Saturday Aug 31st Hurricane Banner Update

pages/profile-beta/index.md
This page will hold the temporary Profile Beta app (https://github.com/department-of-veterans-affairs/vets-website/pull/10663/) that ungates the new
Direct Deposit feature on `prod` for upcoming UAT
=> Add profile-beta page

fragments/home/banner.yml
Hey @ncksllvn 
Here is the latest banner alert message. 
thank you
Josh Tuscher
url:
=> September 4th Hurricane Banner Alert Update

fragments/home/banner.yml
This PR updates the hurricane banner to fix a link and remove a floating `"`.
=> [Banner] Updates per Josh's email

fragments/home/banner.yml
Josh T has instructed us to take down the homepage banner.
=> [Homepage] Remove the banner

pages/disability/after-you-file-claim.md, pages/disability/how-to-file-claim.md
url: https://www.va.gov/disability/how-to-file-claim/
Stakeholder
Update information about time it takes to make a decision on a disability-related claim. The number of days and the month need to be changed.
=> Update info on time to decide a claim

pages/disability/how-to-file-claim/evidence-needed.md
url: https://www.va.gov/disability/how-to-file-claim/evidence-needed/
Stakeholder updates
Move PDF link to farther up page and change wording about the 5103 form.
=> Updating 5103 approach on Evidence Needed page

fragments/home/banner.yml
url: / (homepage)
Email
Ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/1981
Publish a homepage banner
=> [Homepage] Publish banner for Tropical Storm Karen

pages/disability/add-remove-dependent.md, pages/disability/eligibility.md, pages/education/eligibility.md
urls: `/disability/add-remove-dependent`, `/disability/eligibility`, `/education/eligibility`
https://github.com/department-of-veterans-affairs/va.gov-team/issues/1284
Originally [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1284) was meant to add schema.org microtags to the following routes:
```
/disability/add-remove-dependent
/disability/eligibility
/education/eligibility
```
However, we then learned that schema.org microtags were already present in some cases. This PR just sends up some adjustments to those microtags.
=> Kelsonic 1284 update microtags

fragments/home/banner.yml
=> September 26 Banner Update: Removing banner

pages/burials-memorials/veterans-burial-allowance.md
url: https://www.va.gov/burials-memorials/veterans-burial-allowance/
Stakeholder
2019 Rate row needed to be added to two charts and the amounts changes for the 2018 rates.
=> Add 2019 rates to charts

pages/decision-reviews/after-you-request-review.md, pages/decision-reviews/board-appeal.md, pages/decision-reviews/higher-level-review.md, pages/decision-reviews/index.md, pages/decision-reviews/supplemental-claim.md
url: https://www.va.gov/decision-reviews/
https://www.va.gov/decision-reviews/higher-level-review/
https://www.va.gov/decision-reviews/supplemental-claim/
https://www.va.gov/decision-reviews/after-you-request-review/
https://www.va.gov/decision-reviews/board-appeal/
Stakeholder
Edits to reflect SME updates
=> Updating with SME edits

pages/education/school-resources.md
url: http://www.va.gov/education/school-resources/
Story:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19947
SCO Migration Bug
remove extra See full list of Conferences and Events | Training Webinars line
=> removed duplicate line in upcoming events

pages/education/school-resources.md
url:  /education/school-oresource
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19944
Add SCO Events widget
=> SCO events widget

pages/education/school-resources.md
url: /education/school-resources
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19965
As a developer, I need to update the SCO page UI based on UX feedback so that it meets DSVA standards and design practices.
=> SCO: Update UI based on UX team feedback #19965

pages/school-administrators.md
url: /school-administrators 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19967
The Breadcrumb is Home > School administrators.
=> SCO: Update SCO Page BreadCrumble

pages/session-expired.md
url: /session-expired
Slack
This page was removed by accident during a bulk cleanup of vagov-content after Drupal migrations.
=> Restore Session Expired

pages/school-administrators.md
url: /school-administrators
https://github.com/department-of-veterans-affairs/va.gov-team/issues/3055#issuecomment-562310196
We would like to track the **"VA education forms, brochures, and fact sheets"** and **"Required 2019 Training for SCO's"** links as part of our link list convention. 
If we could have the following event code put on those two links we can wrap up 👍
```javascript
dataLayer.push{(
'event': 'nav-linkslist',
'links-list-header': 'Training and Guidelines' //or Policies and Procedures, put the header text here
)};
```
=> Analytics Implementation for Resources for Schools [SCO Migration] #3055

pages/find-va-forms-beta.md
url: /find-va-forms-beta
Me and Kelson 😄 
We need a work-in-progress page to use our Forms React widget before going to production. Right now, Drupal isn't set up to be able to do this without us manually creating the page in Drupal Staging regularly.
=> Add Find VA Forms Beta

fragments/home/banner.yml
=> Removing the banner alert.

fragments/home/banner.yml
=> Coronavirus banner update

fragments/home/banner.yml
=> Latest Corona Virus Update

fragments/home/banner.yml
=> Fixing wrong link

fragments/home/banner.yml
I had to change the banner from “2019-nCoV” to “COVID-19”.
url:
=> Text change to banner alert

pages/decision-reviews/board-appeal.md, pages/decision-reviews/higher-level-review.md, pages/decision-reviews/index.md, pages/decision-reviews/multiple-party-claims.md, pages/decision-reviews/supplemental-claim.md
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/3247
This PR updates the copy on several decision-review pages.
=> Content wip decision reviews updates

fragments/home/banner.yml
=> Corona Update 3

fragments/home/banner.yml
Migrated from https://github.com/department-of-veterans-affairs/vagov-content/pull/632
=> Homepage banner update

pages/decision-reviews/board-appeal.md
url: /decision-reviews/board-appeal/
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6399
Fix text cutoff issue
<details>
<summary>Broken</summary>
</details>
<details>
<summary>Fixed</summary>
</details>
=> [508] Fix for text cutoff

fragments/home/banner.yml
=> 3/20/2020 Coronavirus banner update

fragments/home/banner.yml
https://dsva.slack.com/archives/C52CL1PKQ/p1585758396354500
=> Remove UTM parameters from links in homepage banner

pages/covid-19-virtual-assistant-beta.md
url: /covid-19-virtual-assistant-beta
https://dsva.slack.com/archives/C011BG82ZL6/p1586965257434300
Add a non-prod page for new chatbot to render
=> Add beta page for COVID-19 Virtual Assistant

pages/coronavirus-chatbot.md
url: www.va.gov/coronavirus-chatbot
Implementing recommendations requested from VA.gov public website and platform teams.
Update page path, title, and any copy from `COVID-19 Virtual Assistant` to `Corornavirus chatbot`
=> align page path, page title, copy with rec's

pages/coronavirus-chatbot.md
url: https://dev.va.gov/coronavirus-chatbot/
Demo at 3pm!
- Copy above chatbot window is updated
- <script> link is added instead of npm package in vets-website (cdn version is diff from npm)
- inline styles added (temporary solution)
- webchat id was added to <div> for styles (can be refactored)
=> [#93] Updates text for chatbot and adds script/styles

pages/coronavirus-chatbot.md
url: /coronavirus-chatbot
[Self?](https://dsva.slack.com/archives/C011BG82ZL6/p1587560976018600)
Flip prod flag so page will be viewable to users on va.gov (prod).
=> Flip prod flag on /coronavirus-chatbot to go live on prod at next site deploy

pages/coronavirus-chatbot.md
Just don't ask me why this works. I have no clue.
**Vivaldi:** No regressions I could tell.
**IE 11:** Tested this on my local network and it does the trick. For some reason. :confused:
=> Show the chatbot in IE 11

pages/analytics-opt-out.md
=> Fix spelling error

fragments/home/banner.yml
Hi Nick
Here is another update to the banner. I canceled the last pull request. I also fixed that html error.
url:
=> Another IRS update

pages/coronavirus-chatbot.md
url: coronavirus-chatbot
https://dsva.slack.com/archives/C30LCU8S3/p1588352441261800
Remove the CDN from here and put it in the header so the browser will consistently  load the CDN before the entry point of the app
Sibling PR - https://github.com/department-of-veterans-affairs/vets-website/pull/12460
=> Remove script tag

fragments/home/banner.yml
=> May 6th Banner update

pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#199]
Manually updating the date to reflect most recent changes to FAQ content in the chatbot
=> Updates chatbot date to match FAQ

pages/coronavirus-chatbot.md
Reverts department-of-veterans-affairs/vagov-content#680
=> Revert " Removes inline styles for chatbot page"

pages/coronavirus-chatbot.md
- Added question #57, so updating Last Updated Date to reflect that:
[department-of-veterans-affairs/covid19-chatbot/issues/250]
- Bumping up botframework version to 4.9.0 [changelog](https://github.com/microsoft/BotFramework-WebChat/blob/master/CHANGELOG.md#490---2020-05-11)
[department-of-veterans-affairs/covid19-chatbot/issues/239]
=> Botframework version last updated

pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#259]
=> Updates last updated date on chatbot

pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#253]
Upgrades `botframework-webchat` CDN link to version 4.9.1
Also changes Last Updated Date back to June 4.
=>  upgrades botframework to 4.9.1

pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#276]
Updates Last Updated date to keep in sync with content
=> Chatbot update 6.12

pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#279]
=>  updates chatbot Last Updated Date for 7.2.20 content

pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#288] 
url: https://va.gov/coronavirus-chatbot
=> Updates chatbot last updated date

pages/coronavirus-chatbot.md
[department-of-veterans-affairs/covid19-chatbot#296]
url: http://va.gov/coronavirus-chatbot
=> Bumps botframework version to 4.9.2

pages/coronavirus-chatbot.md
url: va.gov/coronavirus-chatbot
[department-of-veterans-affairs/covid19-chatbot#321]
Updates last updated date to 8/11 to match FAQ page
=> Update chatbot last updated date

pages/form-detail-dummy.md
url: /form-detail-dummy-page
Will be used to test UX of https://github.com/department-of-veterans-affairs/vets-website/pull/13907
=> Add temp dummy page for QAing form detail page

pages/form-detail-dummy.md
url: //form-detail-dummy/
This PR adds a bunch more HTML to create a whole UX for testing the work at https://github.com/department-of-veterans-affairs/va.gov-team/issues/12181
=> [Dummy page] Add more form details for full UX

pages/coronavirus-research.md
=> make link relative

pages/coronavirus-chatbot.md
url: /coronavirus-chatbot
[department-of-veterans-affairs/covid19-chatbot#330]
=> Update coronavirus-chatbot.md Last Updated Date

pages/ask-a-question.md
This will add breadcrumbs to the Contact Us form
url: /ask-a-question (not yet in prod)
department-of-veterans-affairs/orchid#32
=> Adds page for Contact Us (IRIS replacement) form

pages/ask-a-question.md
url: /ask-a-question
[department-of-veterans-affairs/orchid#32]
Updated breadcrumbs to say contact us instead of ask a question
=>  Updates contact us breadcrumbs

pages/coronavirus-chatbot.md
url: /coronavirus-chatbot
[department-of-veterans-affairs/covid19-chatbot#337] 
Upgrade botframework version to 4.11.0
To be merged after sibling vets-website PR
=> Update chatbot botframework version to 4.11.0

pages/my-messages.md
url: /my-messages
[department-of-veterans-affairs/orchid#190]
=> Creates messaging page

pages/playbook/design.html, pages/playbook/design/code.html, pages/playbook/design/components.html, pages/playbook/design/templates.html, pages/playbook/design/visual.html, pages/playbook/editorial.html, pages/playbook/governance.html, pages/playbook/governance/development.html, pages/playbook/human-centered-design.html, pages/playbook/index.html, pages/playbook/migration.html, pages/playbook/platform.html, pages/playbook/product-methodology.html, pages/playbook/product-methodology/alpha.html, pages/playbook/product-methodology/beta.html, pages/playbook/product-methodology/definition.html, pages/playbook/product-methodology/discovery.html, pages/playbook/product-methodology/go-live.html, pages/playbook/product-methodology/kickoff.html, pages/playbook/product-methodology/operations-maintenance.html, pages/playbook/product-methodology/pre-flight.html, pages/playbook/product-methodology/sunset.html
url: https://www.va.gov/playbook/
internal
These pages are no longer being updated, so we want to set them to private to remove them from the global sitemap.
=> Set sitemap pages to private

pages/coronavirus-chatbot.md
=> Updates Covid Chat bot last updated date to April 27 2021

pages/virtual-agent.md
url: staging.va.gov/virtual-agent
department-of-veterans-affairs/va-virtual-agent#137
=> Adds page for virtual agent

pages/virtual-agent.md
url: /virtual-agent-study
[department-of-veterans-affairs/va-virtual-agent#222]
Deletes the virtual-agent.md is not needed anymore and keeping this in would create a blank page on the website at the old url /virtual-agent
=> Deletes virtual-agent.md

fragments/home/banner.yml
**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1625276595441800?thread_ts=1625261383.426000&cid=C52CL1PKQ
This PR updates the homepage banner to not include a `,` after `services` to see if the homepage banner updates in real-time.
=> Remove comma

fragments/home/banner.yml
Reverts department-of-veterans-affairs/vagov-content#774
=> Revert "Remove comma"

fragments/home/banner.yml
=> Tropical Storm Update for VA.gov Home page banner

pages/coronavirus-chatbot.md
=> Updates last updated date for covid chatbot

pages/coronavirus-chatbot.md
url: va.gov/coronavirus-chatbot
Covid 19 chatbot updated
Last updated date s updates
=> Updates covid19 chatbot last updated date

pages/ask-va/index.md
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28848
`/ask-va/`
=> Update ask-va page

pages/coronavirus-chatbot.md
url: va.gov/coronavirus-chatbot
Update last updated date
=> Update last updated date on covid chatbot page

pages/hrt/index.md
url: /hrt/
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35161
Added HRT static page using assets provided
=> HRT page added

pages/hrt/index.md
url: staging.va.gov/hrt/
requested updates from
=> Longmd 35161 hrt content edits

pages/hrt/index.md
url: staging.va.gov/hrt/
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38202
Content markup edits for proper a11y hierarchy
=> Update content heading markup for proper page hierarchy

pages/hrt/index.md
url: https://staging.va.gov/hrt/
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38202
Content edits for typos & bad links
=> HRT Landing Page Content Edits

pages/hrt/index.md
url: https://staging.va.gov/hrt/
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38202
Content edits for typos
=> Fix more HRT content typos

.github/CODEOWNERS
Updating instances of [frontend-review-group](https://github.com/orgs/department-of-veterans-affairs/teams/frontend-review-group) with [platform-release-tools](https://github.com/orgs/department-of-veterans-affairs/teams/platform-release-tools)
department-of-veterans-affairs/va.gov-team#40336
=> Updated codeowners with new FE team

docs/front-matter.md, docs/how-to-edit-content.md, pages/coronavirus-chatbot.md
Updates `master` branch references for the default branch change to `main`.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/41657
=> Update master branch references

pages/school-administrators.md
url: https://www.va.gov/school-administrators/
Tammy Hurley
Formatting error needs to be fixed. Blank line in markdown was causing this:
=> Fixes markdown formatting that was causing defect

.github/CODEOWNERS
=> update references to platform-release-tools to va-platform-cop-frontend

pages/school-administrators.md
https://www.va.gov/school-administrators/
Ticket: Remove "Average Processing Times" from School Administrator webpage [FE]#140
Tammy Hurley
=> RELEASE 1.0.0.0

pages/school-administrators.md
Closes [#166](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/166)
Desktop size:
Mobile size:
=> 166 - Updated the School Administrator webpage description.

pages/school-administrators.md
Closes [229](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/229)
This revision replaces the old "Other resources" section with new content.
=> 229 - update "other resources" section with new content and design

pages/maintenance.md
Updates /maintenance.html. 
This was required for the Redis upgrade, with specific requests from @DanielleThierryUSDSVA and @artsymartha68. The changes were made in coordination with them in a zoom call.
I believe the changes can be merged as is.
=> feat: update maintenance page

pages/school-administrators.md
Closes [#314](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/314)
Adds the Program Approvals section and an inner-page link to it.
**Screenshot:**
=> Add program approvals section and jump link

pages/maintenance.md
url: /maintenance.html
[internal+stakeholder](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/76027)
Maintenance window for Redis upgrade linked above.
=> Updates maintenance.md for upcoming Redis upgrade

pages/school-administrators.md
Closes [#377](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/377)
Screenshot:
=> Update "Understanding Veteran education benefits"

pages/school-administrators.md
Closes [#419](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/419)
Revises the "Program approvals" section with the latest approved content
**Screenshot:**
=> Revise program approvals

pages/school-administrators.md
Closes [#430](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/430)
- This updates the introductory text, "On this page" section, and the sidebar.
- Additionally, some minor language tweaks and typos are fixed
- Changes were also necessary in the `content-build` repository; please see [PR #1948](https://github.com/department-of-veterans-affairs/content-build/pull/1948).
---
**Screenshot 1:**
---
**Screenshot 2:**
=> Resources for Schools Minor Edits

pages/maintenance.md
url: /maintenance.html
PM
Aligns the maintenance date with the planned Redis upgrade
=> Add new maintenance window

pages/school-administrators.md
Closes [#473](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/473).
- Deletes 3 links
- Adds 2 links to the side bar
- Updates 1 link to point to a webpage rather than a PDF
Screenshot of new links:
=> Resources for Schools priority edits

pages/school-administrators.md
Along with [#2071](https://github.com/department-of-veterans-affairs/content-build/pull/2071), closes [#640](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/640)
Adds, subtracts, and edits content. Adds spacing between "Call us" list items.
=> RELEASE 1.2.0

pages/school-administrators.md
url: school administrator
Acceptance Criteria:
- A link is added to the "Ask questions" section of the SCO page on the right sidebar above the Message us.
- A new section "titled SCO Resource Matrix" appears in the "Ask questions" section
- A new link is listed in the SCO Resource Matrix section titled "SCO Resource Matrix"
- The link goes to https://vbatraining.adobeconnect.com/scocontactmatrix/default/index.html
=> VFEP-1499 Add SCO resource subheader, title, and url.

pages/school-administrators.md
url: https://www.va.gov/school-administrators/
Katherine Caruso stakeholder (July 10 2024)
Change label and link of 'Enrollment Manager User Guide' to point
=> vebt-148 #comment Update label and link to Enrollment Manager User Guide

pages/school-administrators.md
url: https://www.va.gov/school-administrators/
As a...
School Certifying Official
I want...
access resources
So that...
I can be knowledgeable
Acceptance Criteria:
•	One the SCO page section at the bottom of the page,  add another link to a va.gov page for students. The link title on the SCO page should be  “How to Use GI Bill Benefits” with caption/explanation  under line link “Learn how students may use their GI Bill benefits to advance their education and training.”
•	It links to the “How to Use My Benefits” page (https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/),   
Technical Details:
Dependencies: No
Feature Flag needed: No
Demo needed: YES
UAT needed: No
Additional Notes: No
Testing Details:
( X ) Quick Turn Around/Direct to Production
(  ) Remains in Staging …
=> VFEP-1671 & VFEP-1672 SCO Add Link to va.gov page for students and Add link to VetSuccess on Campus (VSOC).
